version: 0.2


phases:
  pre_build:   
    commands:
      - echo Current Build number is ${CODEBUILD_BUILD_NUMBER}
      - echo current working dir
      - pwd
      - export IMAGE_NAME=koo-test
      - export ECR_PATH=${REPO_URL}/${IMAGE_NAME}
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 528653706239.dkr.ecr.us-east-1.amazonaws.com
      - REPOSITORY_URI=528653706239.dkr.ecr.us-east-1.amazonaws.com/koo-test
  build:
    commands:
      - echo Docker build ...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - docker images
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"koo-test","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
  files:
    - imagedefinitions.json
